### PR TITLE
HTTPS, projectStuff/autophosphorus

### PR DESCRIPTION
**Pull request by uyjulian**
Stuff should now work again in 2017.

You can click [here](https://github.com/uyjulian/Mega-Scratch-Userscript/raw/master/msu-base.user.js) with Tampermonkey installed to install my fork of the Mega Scratch Userscript.

### CODE REVIEW

**Comment by Airhogs777** [comment]
Ooh :D

**Comment by Firedrake969** [comment]
👍

**Comment by uyjulian** [comment]
I dropped the "remove files" commit and squashed the commit.

**Comment by PullJosh** [comment]
Looks good to me. I'll merge this soon unless there are any objections.

**Pull request merged**
